/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas.formularios;

import Controlador.CRUDCliente;
import Controlador.Conexion;
import Modelo.Cliente;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Usuario
 */
public class frmCliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form frmCliente
     */
    public frmCliente() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator5 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jTextCedula = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextNombres = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextApellidos = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextTelefono = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextSobrenombre = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextDireccion = new javax.swing.JTextField();
        jButtonGuardar = new javax.swing.JButton();
        jButtonActualizar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jSeparator5.setBackground(new java.awt.Color(0, 255, 51));

        setBorder(null);
        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 161, 154));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(7, 81, 74));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/comercio-electronico.png"))); // NOI18N
        jPanel5.add(jLabel7);

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 160, 140));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setFont(new java.awt.Font("Roboto Light", 0, 12)); // NOI18N
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(0, 0, 0));
        jLabel4.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(7, 81, 74));
        jLabel4.setText("Cédula");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, -1, -1));

        jSeparator1.setBackground(new java.awt.Color(0, 255, 51));
        jSeparator1.setForeground(new java.awt.Color(7, 81, 74));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 260, 240, 10));

        jSeparator3.setBackground(new java.awt.Color(0, 255, 51));
        jSeparator3.setForeground(new java.awt.Color(7, 81, 74));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 510, 20));

        jSeparator2.setForeground(new java.awt.Color(7, 81, 74));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 240, 10));

        jSeparator4.setBackground(new java.awt.Color(0, 255, 51));
        jSeparator4.setForeground(new java.awt.Color(7, 81, 74));
        jPanel2.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 510, 10));

        jSeparator6.setBackground(new java.awt.Color(0, 255, 51));
        jSeparator6.setForeground(new java.awt.Color(7, 81, 74));
        jPanel2.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 240, 10));

        jSeparator7.setBackground(new java.awt.Color(0, 255, 51));
        jSeparator7.setForeground(new java.awt.Color(7, 81, 74));
        jPanel2.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, 240, 10));

        jTextCedula.setBorder(null);
        try {
            jTextCedula.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-######-####U")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextCedula.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextCedula.setToolTipText("");
        jTextCedula.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jPanel2.add(jTextCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 510, 40));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(7, 81, 74));
        jLabel5.setText("Nombres");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        jTextNombres.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jTextNombres.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextNombres.setBorder(null);
        jTextNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextNombresKeyTyped(evt);
            }
        });
        jPanel2.add(jTextNombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 240, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(7, 81, 74));
        jLabel6.setText("Apellidos");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));

        jTextApellidos.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jTextApellidos.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextApellidos.setBorder(null);
        jTextApellidos.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextApellidosKeyTyped(evt);
            }
        });
        jPanel2.add(jTextApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 250, 40));

        jLabel8.setBackground(new java.awt.Color(0, 0, 0));
        jLabel8.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(7, 81, 74));
        jLabel8.setText("Dirección");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, 30));

        jTextTelefono.setBorder(null);
        try {
            jTextTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextTelefono.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextTelefono.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jTextTelefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextTelefonoActionPerformed(evt);
            }
        });
        jPanel2.add(jTextTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 250, 40));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(7, 81, 74));
        jLabel9.setText("Sobrenombre");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jTextSobrenombre.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jTextSobrenombre.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSobrenombre.setBorder(null);
        jTextSobrenombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSobrenombreKeyTyped(evt);
            }
        });
        jPanel2.add(jTextSobrenombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 250, 40));

        jLabel10.setBackground(new java.awt.Color(0, 0, 0));
        jLabel10.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(7, 81, 74));
        jLabel10.setText("Teléfono");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, -1, -1));

        jTextDireccion.setFont(new java.awt.Font("Dubai", 0, 18)); // NOI18N
        jTextDireccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextDireccion.setBorder(null);
        jTextDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextDireccionActionPerformed(evt);
            }
        });
        jPanel2.add(jTextDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 510, 40));

        jButtonGuardar.setBackground(new java.awt.Color(250, 178, 53));
        jButtonGuardar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonGuardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/guardar.png"))); // NOI18N
        jButtonGuardar.setText("Guardar");
        jButtonGuardar.setBorder(null);
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonGuardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 120, 50));

        jButtonActualizar.setBackground(new java.awt.Color(250, 178, 53));
        jButtonActualizar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButtonActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/actualizar.png"))); // NOI18N
        jButtonActualizar.setText("Actualizar");
        jButtonActualizar.setBorder(null);
        jButtonActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 350, 120, 50));

        jButton1.setText("Reporte");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 353, 110, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 550, 410));

        jPanel3.setBackground(new java.awt.Color(250, 178, 53));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 81, 74));
        jLabel2.setText("Registrar");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 161, 154));
        jLabel3.setText("Nuevo Cliente");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 550));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextNombresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextNombresKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
                && car != 'á' //Minúsculas
                && car != 'é'
                && car != 'í'
                && car != 'ó'
                && car != 'ú'
                && car != 'Á' //Mayúsculas
                && car != 'É'
                && car != 'Í'
                && car != 'Ó'
                && car != 'Ú'
                && car != 'Ü'
                && car != 'ü'
                && car != 'Ñ'
                && car != 'ñ'
                && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }
    }//GEN-LAST:event_jTextNombresKeyTyped

    private void jTextApellidosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextApellidosKeyTyped
        char car = evt.getKeyChar();
        if ((car < 'a' || car > 'z') && (car < 'A' || car > 'Z')
                && car != 'á' //Minúsculas
                && car != 'é'
                && car != 'í'
                && car != 'ó'
                && car != 'ú'
                && car != 'Á' //Mayúsculas
                && car != 'É'
                && car != 'Í'
                && car != 'Ó'
                && car != 'Ú'
                && car != 'Ü'
                && car != 'ü'
                && car != 'Ñ'
                && car != 'ñ'
                && (car != (char) KeyEvent.VK_SPACE)) {
            evt.consume();
        }

    }//GEN-LAST:event_jTextApellidosKeyTyped

    private void jTextTelefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextTelefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextTelefonoActionPerformed

    private void jTextSobrenombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSobrenombreKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSobrenombreKeyTyped

    private void jTextDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextDireccionActionPerformed

    public void limpiar() {
        jTextCedula.setText("");
        jTextNombres.setText("");
        jTextApellidos.setText("");
        jTextSobrenombre.setText("");
        jTextTelefono.setText("");
        jTextDireccion.setText("");
    }
    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        CRUDCliente cl = new CRUDCliente();
        try {
            if ((jTextCedula.getText().equals("   -      -     "))
                    || (jTextNombres.getText().equals(""))
                    || (jTextApellidos.getText().equals(""))
                    || (jTextTelefono.getText().equals("    -    "))
                    || (jTextSobrenombre.getText().equals(""))
                    || (jTextDireccion.getText().equals(""))) {
                JOptionPane.showMessageDialog(null, "Tiene datos vacíos");
            } else {
                if (cl.verificarDatos(jTextCedula.getText())) {
                    JOptionPane.showMessageDialog(null, "Ya existe cliente con ese número de Cédula");
                } else {
                    guardarCliente();
                    limpiar();
                    JOptionPane.showMessageDialog(null, "Datos Guardados Correctamente");
                    this.dispose();
                    frmGestionarClientes.botonmostrar.doClick();
                }

            }
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    private void jButtonActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActualizarActionPerformed
        try {
            if ((jTextCedula.getText().equals("   -      -     "))
                    || (jTextNombres.getText().equals(""))
                    || (jTextApellidos.getText().equals(""))
                    || (jTextTelefono.getText().equals("    -    "))
                    || (jTextSobrenombre.getText().equals(""))
                    || (jTextDireccion.getText().equals(""))) {
                JOptionPane.showMessageDialog(null, "Tiene datos vacíos");
            } else {
                editarCliente();
                JOptionPane.showMessageDialog(null, "Datos Actualizados Correctamente");
                dispose();

                frmGestionarClientes.botonmostrar.doClick();

            }

        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Error: " + e);
        }
    }//GEN-LAST:event_jButtonActualizarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        Conexion con = new Conexion();
        Connection cn = (Connection) con.conectar();
   
        String path = "C:\\Users\\Usuario\\Desktop\\CrediOHNER\\ProyectoCrediOhner\\src\\Vistas\\Reportes\\report2.jasper";
        JasperReport jr;
        try {
            jr = JasperCompileManager.compileReport(path);
            JasperPrint mostrarReporte = JasperFillManager.fillReport(jr, null, cn);
            JasperViewer.viewReport(mostrarReporte);

        } catch (JRException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton1MouseClicked
    public void guardarCliente() {

        CRUDCliente cc = new CRUDCliente();

        Cliente cl = new Cliente(jTextCedula.getText(),
                jTextNombres.getText(),
                jTextApellidos.getText(),
                jTextSobrenombre.getText(),
                jTextTelefono.getText(),
                jTextDireccion.getText());
        cc.Guardar(cl);

    }

    public void editarCliente() {

        CRUDCliente cc = new CRUDCliente();

        Cliente cl = new Cliente(jTextCedula.getText(),
                jTextNombres.getText(),
                jTextApellidos.getText(),
                jTextSobrenombre.getText(),
                jTextTelefono.getText(),
                jTextDireccion.getText());
        cc.actualizar(cl);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1;
    public static javax.swing.JButton jButtonActualizar;
    public static javax.swing.JButton jButtonGuardar;
    public static javax.swing.JLabel jLabel10;
    public static javax.swing.JLabel jLabel2;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel jLabel6;
    public static javax.swing.JLabel jLabel7;
    public static javax.swing.JLabel jLabel8;
    public static javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel2;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JPanel jPanel5;
    public static javax.swing.JSeparator jSeparator1;
    public static javax.swing.JSeparator jSeparator2;
    public static javax.swing.JSeparator jSeparator3;
    public static javax.swing.JSeparator jSeparator4;
    public static javax.swing.JSeparator jSeparator5;
    public static javax.swing.JSeparator jSeparator6;
    public static javax.swing.JSeparator jSeparator7;
    public static javax.swing.JTextField jTextApellidos;
    public static javax.swing.JFormattedTextField jTextCedula;
    public static javax.swing.JTextField jTextDireccion;
    public static javax.swing.JTextField jTextNombres;
    public static javax.swing.JTextField jTextSobrenombre;
    public static javax.swing.JFormattedTextField jTextTelefono;
    // End of variables declaration//GEN-END:variables
}
