/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas.formularios;

import Controlador.CRUDCliente;
import Vistas.Menu.MDIMenu;
import java.awt.Color;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class frmGestionarClientes extends javax.swing.JInternalFrame {

    int datoSeleccionado = -1;

    public frmGestionarClientes() {
        initComponents();
        mostrar();
        botonmostrar.setVisible(false);
    }

    public void mostrar() {
        try {
            DefaultTableModel modelo;
            CRUDCliente cli = new CRUDCliente();
            modelo = cli.mostrarDatos();
            tableClientes.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonmostrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTextSearch = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableClientes = new javax.swing.JTable();
        jButtonAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setClosable(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonmostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonmostrarActionPerformed(evt);
            }
        });
        getContentPane().add(botonmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(652, 20, 0, 30));

        jPanel1.setBackground(new java.awt.Color(250, 178, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextSearch.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTextSearch.setForeground(new java.awt.Color(153, 153, 153));
        jTextSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSearch.setText("Buscar por cédula, nombres o apellidos");
        jTextSearch.setBorder(null);
        jTextSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextSearchFocusLost(evt);
            }
        });
        jTextSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextSearchMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextSearchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextSearchMouseReleased(evt);
            }
        });
        jTextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearchActionPerformed(evt);
            }
        });
        jTextSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextSearchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextSearchKeyTyped(evt);
            }
        });
        jPanel1.add(jTextSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 570, 40));

        jButtonEliminar.setBackground(new java.awt.Color(0, 161, 154));
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/basura.png"))); // NOI18N
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 50, 40));

        jButtonEditar.setBackground(new java.awt.Color(0, 161, 154));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/lapiz.png"))); // NOI18N
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 50, 40));

        tableClientes.setBackground(new java.awt.Color(187, 227, 222));
        tableClientes.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableClientes.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tableClientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableClientes.setRowHeight(30);
        tableClientes.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tableClientes.setShowGrid(true);
        tableClientes.setShowVerticalLines(false);
        tableClientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableClientesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableClientes);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 760, 330));

        jButtonAgregar.setBackground(new java.awt.Color(0, 161, 154));
        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/agregar.png"))); // NOI18N
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 50, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 510, 20));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 81, 74));
        jLabel2.setText("Gestión de Clientes");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/ReportesGrandes.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, 80));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextSearchMouseClicked
        jTextSearch.setText("");
    }//GEN-LAST:event_jTextSearchMouseClicked

    private void jTextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSearchActionPerformed

    private void jTextSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextSearchMouseReleased

    }//GEN-LAST:event_jTextSearchMouseReleased

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        frmCliente cliente = new frmCliente();
        int x = (MDIMenu.jdpane.getWidth() / 2) - cliente.getWidth() / 2;
        int y = (MDIMenu.jdpane.getHeight() / 2) - cliente.getHeight() / 2;
        cliente.setLocation(x, y);
        MDIMenu.jdpane.add(cliente);
        cliente.toFront();
        frmCliente.jButtonActualizar.setVisible(false);
        cliente.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTextSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextSearchMousePressed
        jTextSearch.setText("");
        jTextSearch.setForeground(Color.black);
    }//GEN-LAST:event_jTextSearchMousePressed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

        if (datoSeleccionado >= 0) {
            String dato = String.valueOf(tableClientes.getValueAt(datoSeleccionado, 0));
            CRUDCliente cli = new CRUDCliente();
            if (JOptionPane.showConfirmDialog(rootPane,
                    "Se eliminará el registro, ¿desea continuar?",
                    "Eliminar Registro",
                    JOptionPane.WARNING_MESSAGE,
                    JOptionPane.YES_NO_OPTION)
                    == JOptionPane.YES_OPTION) {
                cli.eliminar(dato);
                mostrar();
                JOptionPane.showMessageDialog(null,
                        "Dato eliminado correctamente");
            }
        } else {
            JOptionPane.showMessageDialog(null,
                    "Debe seleccionar un registro de la tabla");
        }


    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void tableClientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableClientesMouseClicked
        datoSeleccionado = tableClientes.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tableClientesMouseClicked

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        frmCliente cliente = new frmCliente();
        int x = (MDIMenu.jdpane.getWidth() / 2) - cliente.getWidth() / 2;
        int y = (MDIMenu.jdpane.getHeight() / 2) - cliente.getHeight() / 2;
        cliente.setLocation(x, y);
        MDIMenu.jdpane.add(cliente);

        if (datoSeleccionado >= 0) {
            //mandar datos al formulario
            frmCliente.jTextCedula.setText(String.valueOf(tableClientes.getValueAt(datoSeleccionado, 0)));
            frmCliente.jTextNombres.setText(String.valueOf(tableClientes.getValueAt(datoSeleccionado, 1)));
            frmCliente.jTextApellidos.setText(String.valueOf(tableClientes.getValueAt(datoSeleccionado, 2)));
            frmCliente.jTextSobrenombre.setText(String.valueOf(tableClientes.getValueAt(datoSeleccionado, 3)));
            frmCliente.jTextTelefono.setText(String.valueOf(tableClientes.getValueAt(datoSeleccionado, 4)));
            frmCliente.jTextDireccion.setText(String.valueOf(tableClientes.getValueAt(datoSeleccionado, 5)));
            frmCliente.jTextCedula.enable(false);
            //hacer al frente y visible
            cliente.toFront();
            frmCliente.jButtonGuardar.setVisible(false);
            cliente.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro a actualizar");
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void botonmostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonmostrarActionPerformed
        mostrar();
    }//GEN-LAST:event_botonmostrarActionPerformed

    private void jTextSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSearchKeyReleased
        buscar();
    }//GEN-LAST:event_jTextSearchKeyReleased

    private void jTextSearchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSearchKeyTyped

    }//GEN-LAST:event_jTextSearchKeyTyped

    private void jTextSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSearchFocusLost
        jTextSearch.setText("Buscar por cédula, nombres o apellidos");
        jTextSearch.setForeground(Color.gray);
    }//GEN-LAST:event_jTextSearchFocusLost
    public void buscar() {
        try {
            DefaultTableModel modelo;
            CRUDCliente cli = new CRUDCliente();
            modelo = cli.buscarDatos(jTextSearch.getText());
            tableClientes.setModel(modelo);
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton botonmostrar;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextSearch;
    private javax.swing.JTable tableClientes;
    // End of variables declaration//GEN-END:variables
}
