/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Vistas.formularios;

import Controlador.CRUDGarantia;
import Vistas.Menu.MDIMenu;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Usuario
 */
public class frmGestionarGarantias extends javax.swing.JInternalFrame {

    int datoSeleccionado=-1;


    public frmGestionarGarantias() {
        initComponents();
        mostrar();

        
    }

    public void mostrar() {
        try {
            DefaultTableModel modelo;
            CRUDGarantia gr = new CRUDGarantia();
            modelo = gr.mostrarDatos();
            tableGarantias.setModel(modelo);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTextSearch = new javax.swing.JTextField();
        jButtonEliminar = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableGarantias = new javax.swing.JTable();
        jButtonAgregar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonAct = new javax.swing.JButton();

        setClosable(true);

        jPanel1.setBackground(new java.awt.Color(250, 178, 53));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextSearch.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        jTextSearch.setForeground(new java.awt.Color(153, 153, 153));
        jTextSearch.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextSearch.setText("Escribe el nombre de la garantía a buscar");
        jTextSearch.setBorder(null);
        jTextSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jTextSearchFocusLost(evt);
            }
        });
        jTextSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextSearchMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jTextSearchMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTextSearchMousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTextSearchMouseReleased(evt);
            }
        });
        jTextSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextSearchActionPerformed(evt);
            }
        });
        jTextSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextSearchKeyReleased(evt);
            }
        });
        jPanel1.add(jTextSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 570, 40));

        jButtonEliminar.setBackground(new java.awt.Color(0, 161, 154));
        jButtonEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/basura.png"))); // NOI18N
        jButtonEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEliminarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 130, 50, 40));

        jButtonEditar.setBackground(new java.awt.Color(0, 161, 154));
        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/lapiz.png"))); // NOI18N
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEditar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 50, 40));

        tableGarantias.setBackground(new java.awt.Color(187, 227, 222));
        tableGarantias.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        tableGarantias.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        tableGarantias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableGarantias.setRowHeight(30);
        tableGarantias.setSelectionBackground(new java.awt.Color(0, 0, 0));
        tableGarantias.setShowGrid(true);
        tableGarantias.setShowVerticalLines(false);
        tableGarantias.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableGarantiasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableGarantias);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 760, 330));

        jButtonAgregar.setBackground(new java.awt.Color(0, 161, 154));
        jButtonAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/agregar.png"))); // NOI18N
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 50, 40));

        jSeparator1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 570, 20));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(7, 81, 74));
        jLabel2.setText("Gestión de Garantías");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vistas/iconos/garantia grande.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 70, 80));

        jButtonAct.setText("jButton1");
        jButtonAct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAct, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 50, 0, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextSearchMouseClicked
        jTextSearch.setText("");
    }//GEN-LAST:event_jTextSearchMouseClicked

    private void jTextSearchMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextSearchMousePressed
        jTextSearch.setText("");
        jTextSearch.setForeground(Color.black);
    }//GEN-LAST:event_jTextSearchMousePressed

    private void jTextSearchMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextSearchMouseReleased

    }//GEN-LAST:event_jTextSearchMouseReleased

    private void jTextSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextSearchActionPerformed

    private void jButtonEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEliminarActionPerformed

        if (datoSeleccionado >= 0) {
            int dato = Integer.parseInt((String)tableGarantias.getValueAt(datoSeleccionado, 0));
            CRUDGarantia gr = new CRUDGarantia();
            if (JOptionPane.showConfirmDialog(rootPane,
                "Se eliminará el registro, ¿desea continuar?",
                "Eliminar Registro",
                JOptionPane.WARNING_MESSAGE,
                JOptionPane.YES_NO_OPTION)
            == JOptionPane.YES_OPTION) {
            gr.eliminar(dato);
            mostrar();
            JOptionPane.showMessageDialog(null,
                "Dato eliminado correctamente");
        }
        } else {
            JOptionPane.showMessageDialog(null,
                "Debe seleccionar un registro de la tabla");
        }

    }//GEN-LAST:event_jButtonEliminarActionPerformed

    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
        frmGarantias g = new frmGarantias();
        int x = (MDIMenu.jdpane.getWidth() / 2) - g.getWidth() / 2;
        int y = (MDIMenu.jdpane.getHeight() / 2) - g.getHeight() / 2;
        g.setLocation(x, y);
        MDIMenu.jdpane.add(g);

        if (datoSeleccionado >= 0) {
            frmGarantias.jTextNombre.setText(String.valueOf(tableGarantias.getValueAt(datoSeleccionado,1)));
            frmGarantias.jTextObservacion.setText(String.valueOf(tableGarantias.getValueAt(datoSeleccionado,2)));
            frmGarantias.jlabelcod.setText(String.valueOf(tableGarantias.getValueAt(datoSeleccionado,0)));
            g.toFront();
            frmGarantias.jButtonGuardar.setVisible(false);
            g.setVisible(true);
        } else {
            JOptionPane.showMessageDialog(null, "Debe seleccionar un registro a actualizar");
        }
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void tableGarantiasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableGarantiasMouseClicked
        datoSeleccionado = tableGarantias.rowAtPoint(evt.getPoint());
    }//GEN-LAST:event_tableGarantiasMouseClicked

    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        frmGarantias g = new frmGarantias();
        int x = (MDIMenu.jdpane.getWidth() / 2) - g.getWidth() / 2;
        int y = (MDIMenu.jdpane.getHeight() / 2) - g.getHeight() / 2;
        g.setLocation(x, y);
        MDIMenu.jdpane.add(g);
        g.toFront();
        frmGarantias.jButtonActualizar.setVisible(false);
        g.setVisible(true);
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    private void jTextSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextSearchKeyReleased
        try {
            DefaultTableModel modelo;
            CRUDGarantia cg = new CRUDGarantia();
            modelo = cg.MostrarDatos(jTextSearch.getText());
            mostrar();
            tableGarantias.setModel(modelo);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jTextSearchKeyReleased

    private void jTextSearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextSearchMouseExited

    }//GEN-LAST:event_jTextSearchMouseExited

    private void jTextSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextSearchFocusLost
        jTextSearch.setText("Escriba el nombre de la garantia a buscar");
        jTextSearch.setForeground(Color.GRAY);
    }//GEN-LAST:event_jTextSearchFocusLost

    private void jButtonActActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActActionPerformed
        mostrar();
    }//GEN-LAST:event_jButtonActActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButtonAct;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonEliminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextSearch;
    private javax.swing.JTable tableGarantias;
    // End of variables declaration//GEN-END:variables
}
